# Generated by Django 3.0.6 on 2020-06-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
    ]
