# Generated by Django 3.0.7 on 2020-06-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminModule', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.CharField(max_length=30),
        ),
    ]
